import { Brand, Product } from '../types/Product';

export const BRANDS: Brand[] = [
  {
    id: 'mac',
    name: 'MAC',
    logoUrl: '',
    affiliateBaseUrl: 'https://www.maccosmetics.com',
    accentColor: '#000000',
  },
  {
    id: 'fenty',
    name: 'Fenty Beauty',
    logoUrl: '',
    affiliateBaseUrl: 'https://www.fentybeauty.com',
    accentColor: '#E8453C',
  },
  {
    id: 'nars',
    name: 'NARS',
    logoUrl: '',
    affiliateBaseUrl: 'https://www.narscosmetics.com',
    accentColor: '#C8A882',
  },
  {
    id: 'charlotte',
    name: 'Charlotte Tilbury',
    logoUrl: '',
    affiliateBaseUrl: 'https://www.charlottetilbury.com',
    accentColor: '#B76E79',
  },
  {
    id: 'maybelline',
    name: 'Maybelline',
    logoUrl: '',
    affiliateBaseUrl: 'https://www.maybelline.com',
    accentColor: '#E32636',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'mac-ruby-woo',
    name: 'Ruby Woo',
    brand: BRANDS[0],
    category: 'lips',
    colorHex: '#9B1B30',
    colorName: 'Classic Red',
    price: 23,
    purchaseUrl: 'https://www.maccosmetics.com/product/ruby-woo',
    imageUrl: '',
    compatibleSkinTones: ['fair', 'light', 'medium', 'tan', 'deep', 'rich'],
  },
  {
    id: 'fenty-uncensored',
    name: 'Uncensored',
    brand: BRANDS[1],
    category: 'lips',
    colorHex: '#7B2D3E',
    colorName: 'Deep Berry',
    price: 26,
    purchaseUrl: 'https://www.fentybeauty.com/product/uncensored',
    imageUrl: '',
    compatibleSkinTones: ['medium', 'tan', 'deep', 'rich'],
  },
  {
    id: 'nars-dragon-girl',
    name: 'Dragon Girl',
    brand: BRANDS[2],
    category: 'lips',
    colorHex: '#C0392B',
    colorName: 'Vivid Red',
    price: 28,
    purchaseUrl: 'https://www.narscosmetics.com/product/dragon-girl',
    imageUrl: '',
    compatibleSkinTones: ['light', 'medium', 'tan'],
  },
  {
    id: 'charlotte-pillow-talk',
    name: 'Pillow Talk',
    brand: BRANDS[3],
    category: 'lips',
    colorHex: '#C4847A',
    colorName: 'Soft Pink Nude',
    price: 34,
    purchaseUrl: 'https://www.charlottetilbury.com/product/pillow-talk',
    imageUrl: '',
    compatibleSkinTones: ['fair', 'light', 'medium'],
  },
  {
    id: 'maybelline-rich-ruby',
    name: 'Rich Ruby',
    brand: BRANDS[4],
    category: 'lips',
    colorHex: '#872341',
    colorName: 'Deep Ruby',
    price: 10,
    purchaseUrl: 'https://www.maybelline.com/product/rich-ruby',
    imageUrl: '',
    compatibleSkinTones: ['tan', 'deep', 'rich'],
  },
  {
    id: 'fenty-sheer-mango',
    name: 'Sheer Mango',
    brand: BRANDS[1],
    category: 'lips',
    colorHex: '#E8825A',
    colorName: 'Warm Coral',
    price: 26,
    purchaseUrl: 'https://www.fentybeauty.com/product/sheer-mango',
    imageUrl: '',
    compatibleSkinTones: ['medium', 'tan', 'deep', 'rich'],
  },
];